kernel/blog/urls.py
from django.urls import path
from . import views
app_name = 'blog'
urlpatterns = [
    path('posts/', views.PostListView.as_view(), name = 'posts'),
    path('post/<slug:slug>', views.PostDetailView.as_view(), name = 'post'),
    path('bosses/', views.BossListView.as_view(), name = 'bosses'),
    path('boss/example/', views.BossDetailView.as_view(), name = 'boss'),


]

kernel/mysite/urls.py
from django.urls import path
from . import views
app_name="mysite"
urlpatterns=[
    path('', views.HomeView.as_view(), name = 'landing'),
    # path('product_n', views.ProductView.as_view(), name = 'product_new'),
    path('posts/', views.PostListView.as_view(), name="posts"),
    # # path('product_n/', views.details2, name ='product_new'),
    # path('product/<str:title>', views.detail, name = 'product'),
    # path('post/<slug:slug>', views.PostDetailView.as_view(), name="post"),
]

kernel/media/templates/partials/_footer.html
<footer class="banner_3">
    <div class="the-border relative">
        <div class="container-fluid">
            <div class="row">
                <div class="heavy-color col-3 col-sm-3"></div>
                <div class="light-color col-9 col-sm-9"></div>
            </div>
        </div>
    </div>
    <div class="container py-5">
        <div class="row no_margin">
            <div class="col-12">
                <h4 class="heading-style-3 footer-brand">Badminton <span>logo</span></h4>
                <ul class="list-inline mb-0 social-media">
                    <li class="list-inline-item"><a class="youtube" href="#"><i class="fa fa-youtube-play hvr-grow"
                                aria-hidden="true"></i></a></li>
                    <li class="list-inline-item"><a class="facebook" href="#"><i class="fa fa-facebook-square hvr-grow"
                                aria-hidden="true"></i></a></li>
                    <li class="list-inline-item"><a class="linkedin" href="#"><i class="fa fa-linkedin hvr-grow"
                                aria-hidden="true"></i></a></li>
                    <li class="list-inline-item"><a class="google-plus" href="#"><i class="fa fa-google-plus hvr-grow"
                                aria-hidden="true"></i></a></li>
                </ul>
            </div>
            <div class="col-12">
                <p class="text">لورم ایپسوم متن ساختگی با تولید سادگی نامفهوم از صنعت چاپ و با استفاده از طراحان گرافیک
                    است. چاپگرها و متون بلکه روزنامه و مجله در ستون و سطرآنچنان که لازم است و برای شرایط فعلی تکنولوژی
                    مورد نیاز و کاربردهای متنوع با هدف بهبود ابزارهای کاربردی می باشد. کتابهای زیادی در شصت و سه درصد
                    گذشته، حال و آینده شناخت فراوان جامعه و متخصصان را می طلبد</p>
            </div>
            <div class="col-12">
                <div class="row">
                    <div class="col-sm-12 col-md-6 col-lg-5 news-letter">
                        <h3 class="heading-style-4">خبرنامه</h3>
                        <form class="form-inline">
                            <div class="form-group mb-2">
                                <input class="form-control" placeholder="ایملیل شما">
                            </div>
                            <button type="submit" class="btn_1">اشتراک</button>
                        </form>
                    </div>
                    <div class="col-lg-1 d-none d-lg-block"></div>
                    <div class="d-none d-md-block col-md-6 col-lg-6 last-match-carousel">
                        <h3 class="heading-style-4">خبرنامه</h3>
                        <div id="owl-five" class="owl-carousel owl-theme">
                            <div class="item">
                                <p>ایران <span>VS</span> چین</p>
                                <a href="#"><i class="fa fa-angle-left" aria-hidden="true"></i>بیشتر بخوانید</a>
                            </div>
                            <div class="item">
                                <p>ایران <span>VS</span> چین</p>
                                <a href="#"><i class="fa fa-angle-left" aria-hidden="true"></i>بیشتر بخوانید</a>
                            </div>
                            <div class="item">
                                <p>ایران <span>VS</span> چین</p>
                                <a href="#"><i class="fa fa-angle-left" aria-hidden="true"></i>بیشتر بخوانید</a>
                            </div>
                            <div class="item">
                                <p>ایران <span>VS</span> چین</p>
                                <a href="#"><i class="fa fa-angle-left" aria-hidden="true"></i>بیشتر بخوانید</a>
                            </div>
                            <div class="item">
                                <p>ایران <span>VS</span> چین</p>
                                <a href="#"><i class="fa fa-angle-left" aria-hidden="true"></i>بیشتر بخوانید</a>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
            <div class="footer-divider"></div>
            <div class="col-12">
                <div class="navbar-footer">
                    <ul class="list-inline">
                        <li class="list-inline-item"><a href="#">لینک</a></li>
                        <li class="list-inline-item"><a href="#">لینک</a></li>
                        <li class="list-inline-item"><a href="#">لینک</a></li>
                        <li class="list-inline-item"><a href="#">لینک</a></li>
                        <li class="list-inline-item"><a href="#">لینک</a></li>
                    </ul>
                </div>
                <p class="copyright">Copyright &copy; Sageteam</p>
            </div>
        </div>
    </div>
</footer>

kernel/media/templates/partials/_header.html
<div class="header-one font-thin">
    <div class="container-fluid">
        <div class="row">
            <div class="col-md-7 col-lg-6">
                <ul class="list-inline">
                    <li class="list-inline-item">
                        <h3 class="heading-style-3 mr-bt-0"><a class="sa_white_link" href="#">درباره ما</a></h3>
                    </li>
                    <li class="list-inline-item">
                        <h3 class="heading-style-3 mr-bt-0"><a class="sa_white_link" href="#">بازیکن های ثبت شده</a></h3>
                    </li>
                </ul>
            </div>
            <div class="col-md-5 col-lg-6">
                <h3 class="heading-style-3 mr-bt-0 text-left">
                    <a class="sa_white_link" href="#">حساب کاربری</a>
                </h3>
            </div>
        </div>
    </div>
</div>
<div class="header-two">
    <div class="container-fluid">
        <div class="row">
            <div class="d-none d-lg-block d-xl-block col-lg-1"></div>
            <div class="col-md-3 col-lg-3">
                <form class="form-inline my-2 my-lg-0">
                    <input class="form-control mr-sm-2" type="text" placeholder="جستجو کنید ...">
                </form>
            </div>
            <div class="col-md-6 col-lg-5">
                <ul class="list-inline sa_header_contact_texts">
                    <li class="list-inline-item">
                        <p class="white">تماس با ما</p>
                        <a class="sa_white_link" href="#">org.demolink@f</a>
                    </li>
                    <li class="list-inline-item">
                        <p class="white">درخواست عضویت در تیم
                        </p>
                        <a class="sa_white_link" href="#">org.demolink@f</a>
                    </li>
                </ul>
            </div>
            <div class="col-md-3 col-lg-3">
                <div class="sa_black_box center-box"></div>
            </div>
            <div class="d-none d-lg-block d-xl-block col-lg-1"></div>
        </div>
    </div>
</div>

kernel/media/templates/partials/_nav.html
<nav class="navbar navbar-expand-lg navbar-dark bg-primary font-thin">
        <a class="navbar-brand {% if view.page_name == 'landing' %}active{% endif %}" href="{% url 'mysite:landing' %}">خانه بدمینتون</a>
        <button class="navbar-toggler d-none d-md-block d-lg-none d-xl-none" type="button" data-toggle="collapse" data-target="#navbarColor01" aria-controls="navbarColor01" aria-expanded="false" aria-label="Toggle navigation">
          <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarColor01">
          <ul class="navbar-nav mr-auto">
            <li class="nav-item">
              <a class="nav-link" href="#">لیگ <span class="sr-only">(current)</span></a>
            </li>
            <li class="nav-item">
              <a class="nav-link" href="#">اخبار</a>
            </li>
            <li class="nav-item">
              <a class="nav-link" href="#">آموزش</a>
            </li>
            <li class="nav-item">
              <a class="nav-link" href="#">باشگاه ها</a>
            </li>
            <li class="nav-item dropdown">
              <a class="nav-link dropdown-toggle" data-toggle="dropdown" href="#" id="download"><i class="fa fa-caret-down" aria-hidden="true"></i>هیئت بدمینتون</a>
              <div class="dropdown-menu" aria-labelledby="download">
                <a class="dropdown-item" href="https://jsfiddle.net/bootswatch/h3fgn55j/">چارت سازمانی استان مازندران</a>
                <div class="dropdown-divider"></div>
                <a class="dropdown-item" href="../4/cosmo/bootstrap.min.css">رئسای استان مازندران</a>
                <div class="dropdown-divider"></div>
                <a class="dropdown-item" href="../4/cosmo/_variables.scss">سخنان بزرگان بدمینتون</a>
              </div>
            </li>
            <li class="nav-item">
              <a class="nav-link" href="#">فروشگاه</a>
            </li>
          </ul>
        </div>
        <div class="sa-header-button d-block d-md-none d-lg-none d-xl-none">
          <i class="fa fa-bars" aria-hidden="true"></i>
        </div>
        <div class="sa-header-button search d-block d-md-none d-lg-none d-xl-none">
          <i class="fa fa-search" aria-hidden="true"></i>
        </div>
      </nav>
      <div class="cssmenu dark-bg">
        <ul>
          <li class="sa-close-btn"><i class="fa fa-times" aria-hidden="true"></i></li>
          <li>
            <input type="email" class="form-control" id="exampleInputEmail1" placeholder="جستجو کنید ...">
          </li>
          <li class="navbar-brand active">خانه بدبینتون</li>
          <li class=""><a class="list" href="#"><span>لیگ</span></a></li>
          <li class=""><a class="list" href="#"><span>مسابقات</span></a></li>
          <li class=""><a class="list" href="#"><span>بازیکنان</span></a></li>
          <li class=""><a class="list" href="#"><span>حساب کاربری</span></a></li>
        </ul>
      </div>

kernel/media/templates/partials/_navigation.html
<nav>
    <ul>
        <li>home</li>
        <li>product</li>
        <li>store</li>
        <li>about us</li>

    </ul>
</nav>