kernel/blog/urls.py
from django.urls import path
from . import views
app_name = 'blog'
urlpatterns = [
    path('posts/', views.PostListView.as_view(), name = 'posts'),
    path('post/<slug:slug>', views.PostDetailView.as_view(), name = 'post'),
    path('bosses/', views.BossListView.as_view(), name = 'bosses'),
    path('boss/example/', views.BossDetailView.as_view(), name = 'boss'),


]

kernel/blog/models.py
import uuid
import secrets
from django.db import models
from django.utils import timezone
from django.contrib.auth.models import User
from painless.models import choices as options
from painless.models.mixins import OrganizedMixin
from painless.models.mixins import TimeStampedMixin
from painless.models.managers import PostPublishedManager

status = options.PostStatus(is_charfield = False)
# Create your models here.

class Tag(OrganizedMixin):
    class Meta:
        ordering = [ '-created' ]

    def __str__(self):
        return self.title
 

class Category(OrganizedMixin):
    class Meta:
        ordering = ['-created']
        verbose_name = 'category'
        verbose_name_plural = 'categories'
    
        
    def __str__(self):
        return self.title

class Post(TimeStampedMixin):
    uid = models.UUIDField(primary_key = True, default = uuid.uuid4, editable = False)
    title = models.CharField(max_length = 128, unique_for_month='published_at', help_text = 'must be unique')
    slug = models.CharField(max_length = 128, unique_for_month='published_at')
    banner = models.ImageField(upload_to = 'blog', null = True, blank = True)
    summary = models.CharField(max_length = 128)
    content = models.TextField()
    status = models.PositiveSmallIntegerField(choices = status.get_status(), default = status.DRAFT)
    # status = models.PositiveSmallIntegerField(choices = POST_STATUS, default = DRAFT)


    tag = models.ManyToManyField('Tag', related_name = 'post')
    author = models.ForeignKey(User, on_delete = models.CASCADE, related_name = 'posts')
    category = models.ForeignKey('Category', on_delete=models.PROTECT, related_name = 'posts')


    published_at = models.DateTimeField(default=timezone.now())
    

    objects = models.Manager()
    condition = PostPublishedManager()

    class Meta:
        ordering = ['-published_at', 'title']
        verbose_name = 'post'
        verbose_name_plural = 'posts'
        get_latest_by = ['-published_at']

    def __str__(self):
        return self.title

# class Comment(TimeStampedModel):
#     commented_by = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete = models.CASCADE)
#     for_post = models.ForeignKey(Post, related_name='comments', on_delete = models.CASCADE)
#     parent = models.ForeignKey("self", null = True, blank = True, on_delete = models.SET_NULL)
#     content = models.TextField()
#     status = models.PositiveSmallIntegerField(choices=opt_status.get_status(), default = opt_status.PUDBLISHED)

#     class Meta:
#         ordering = ['-created']
#         verbose_name = 'comment'
#         verbose_name_plural = 'comments'
    
    
#     def __str__(self): 
#         return self.for_post.title




class Comment(TimeStampedMixin):
    post = models.ForeignKey(Post, on_delete = models.CASCADE, related_name='comments')
    title = models.CharField(max_length= 128, unique = True)
    email = models.EmailField()
    content = models.TextField()
    active = models.BooleanField(default=True)
    reply_to = models.ForeignKey('self',null=True, blank=True, on_delete=models.CASCADE, related_name='replies')

    class Meta:
        ordering = ('created',)
        verbose_name = 'comment'
        verbose_name_plural = 'comments'
        get_latest_by = ['-created']

    def __str__(self):
        return 'Comment by {} on {}'.format(self.title, self.post) 

kernel/product/models.py
from django.db import models
from django.utils import timezone
from django.contrib.auth.models import User
from painless.models import choices as options
from painless.models.mixins import OrganizedMixin
from painless.models.mixins import TimeStampedMixin

status = options.PostStatus(is_charfield = False)
class Size(OrganizedMixin):
    SHIRT_SIZE = (
        ('xS', 'XtraSmall'),
        ('S','Small'),
        ('M', 'Medium'),
        ('L', 'Large'),
        ('XL', 'XtraLarge'),
    )
    class Meta:
        ordering = ('title',)
        verbose_name = 'size'
        verbose_name_plural = 'sizes'
        
class ProductCatalog(OrganizedMixin):
    # picture = models.ManyToManyField(Image, null = True, blank = True, on_delete = models.CASCADE )
    price = models.DecimalField(default='0.0', max_digits=10, decimal_places=2)
    content = models.TextField()
    # shirt_size = models.CharField(max_length=1, choices=SHIRT_SIZE)
    # size = models.ForeignKey('FIlter', on_delete=models.PROTECT)
    COLOR_CHOICES =(
        (u'blue', 'blue'),
        (u'green', 'green'),
        (u'red', 'red')
    )
    color_choices = models.CharField(max_length=1, choices=COLOR_CHOICES)
    status = models.PositiveSmallIntegerField(choices = status.get_status(), default = status.DRAFT)
    published_at = models.DateTimeField(default=timezone.now())    
    banner = models.ImageField(upload_to='products/%Y/%m/%d', blank=True)

    def __str__(self):
        return self.title
    class Meta:
        ordering = ('created',)
        verbose_name = 'product'
        verbose_name_plural = 'products'
        get_latest_by = ['-published_at']
        
class ProductType(OrganizedMixin):
    productID = models.ForeignKey('ProductCatalog', on_delete = models.CASCADE,)
    typeTitle = models.CharField(max_length=200)


class Product_subType(OrganizedMixin):
    typeID = models.ForeignKey('ProductType', on_delete = models.CASCADE,)
    subType_title = models.CharField(max_length=200 , null=False, blank=False)    

kernel/blog/views.py
from django.views.generic import ListView, DetailView, TemplateView
from .models import Post
class PostListView(ListView):
    model = Post
    template_name = 'blog/post_list.html'
    context_object_name = 'posts'

class PostDetailView(DetailView):
    model = Post
    template_name = 'blog/post.html'
    context_object_name = 'post'

class BossListView(TemplateView):
    # model = Boss
    template_name = 'blog/boss_list.html'
    # context_object_name = 'booses'

class BossDetailView(TemplateView):
    # model = Post
    template_name = 'blog/boss_detail.html'
    # context_object_name = 'boss'

# class PrductListView(ListView):
#     template_name = 'mysite/product_new.html'
#     page_name = 'product_new'

kernel/product/views.py
from django.shortcuts import render

# Create your views here.

kernel/media/templates/blog/boss_detail.html
{% extends 'shared/master.html' %}
{% load static %}
{% block body %}
<main>
    <div class="banner_3">
      <h1 class="heading-style-1">
        اخبار
      </h1>
      <div class="location">
        <a href="#">خانه</a>
        <span>/</span>
        <a href="#">اخبار</a>
        <span>/</span>
        <a href="#">لیست اخبار با نوار کناری</a>
        <span>/</span>
        <a class="active" href="#">لیست</a>
      </div>
    </div>

    <div class="news-section specific-news boss-person">
      <div class="container">
        <div class="row">
          <div class="col-lg-8 right_side news-list">
            <div class="col-12">
              <div class=" border-box-2 specified-news">
                <div class="row">
                  <div class="col-md-12">
                    <div class="display-flex-r mx-0">
                      <img src="{% static 'assets/img/thumb/profile.jpg' %}" alt="{{ post.author.first_name }} {{ post.author.last_name }}">
                      <span class="name">{{ boss.author.first_name }} {{ boss.author.last_name }}</span>
                         <!-- src="assets/img/thumb/profile.jpg" alt=""> -->
                      </div>
                      <div class="news-content">
                        <a class="title" href="{% url 'blog:boss' slug=boss.slug %}">{{ boss.title }}</a>
                        <br>
                        <span class="date">{{ boss.published_at}}</span>
                        <p class="text mt-4">تحصیلات : </p>
                        <p class="text">۱۳۹۵ / ۶ / ۱۲ : فعالیت ش</p>
                        <hr class="hr-divider-1 mt-4">
                        <hr class="hr-divider-2">
                        <div class="social">
                          <div class="user-input seen-count">
                            <i class="fa fa-eye" aria-hidden="true"></i>
                            <span class="count">251</span>
                          </div>
                            <div class="user-input like liked">
                              <button class="like liked" href="#" role="button">
                                <i class="fa fa-heart-o" aria-hidden="true"></i>
                                <i class="fa fa-heart" aria-hidden="true"></i>
                              </button>
                              <span class="count">251</span>
                            </div>
                        </div>
                      </div>
                    </div>
                  </div>
                  <div class="simple-divider mt-0"></div>
                  <div class="post-content">
                    <p class="text">{{ post.content }}
                    </p>
                  </div>
                  <div class="simple-divider"></div>
                  {% for tag in post.tag.all %}
                  {% if forloop.firs %}
                    <div class="ticket-1">
                    <a class=" unknown-btn d-none d-sm-block" href="#">{{ tag.title }}</a>
                  </div>
                  {% else%}
                  <div class="ticket-1 ml-2">
                      <a class=" unknown-btn d-none d-sm-block" href="#">{{tag.title}}</a>
                    </div>
                    {% endif %}
                    {% endfor%}
                  <ul class="pagination post">
                    <li class="page-item"><a class="page-link" href="#"><i class="fa fa-telegram" aria-hidden="true"></i></a></li>
                    <li class="page-item"><a class="page-link no-smoth" href="#"><i class="fa fa-telegram" aria-hidden="true"></i></a></li>
                    <li class="page-item"><a class="page-link" href="#"><i class="fa fa-telegram" aria-hidden="true"></i></a></li>
                  </ul>
                </div>
              </div>
            </div>
          </div>
          <div class="col-lg-4 left_side">
            <div class="col-md-12">
              <div class="border-box-2 overflow_hidden">
                <div class="header-section">
                  <div class="row">
                    <div class="col-6">
                      <h3 class="heading-style-3">خبر جدید</h3>
                    </div>
                    <div class="col-6"></div>
                  </div>
                </div>
                <div id="owl-seven" class="owl-carousel owl-theme">
                  <div class="item">
                    <img src="{% static 'assets/img/thumb/profile.jpg' %}" alt="" />
                    <h5 class="text-center">جام کشوری</h5>
                    <p class="date text-center">۱۳۹۷ . تیر ۳۱</p>
                  </div>
                  <div class="item">
                    <img src="{% static 'assets/img/thumb/profile.jpg' %}" alt="" />
                    <h5 class="text-center">جام کشوری</h5>
                    <p class="date text-center">۱۳۹۷ . تیر ۳۱</p>
                  </div>
                </div>
              </div>

              <div class="new-news border-box-2 overflow_hidden mt-4 d-none d-lg-block">
                <div class="header-section">
                  <div class="row">
                    <div class="col-6">
                      <h3 class="heading-style-3">خبر جدید</h3>
                    </div>
                    <div class="col-6"></div>
                  </div>
                </div>
                <div class="row">
                  <div class="col-12 col-md-6 col-lg-12 item">
                    <div class="row">
                      <div class="col-4">
                        <a href="#"><img class="img-fluid" src="{% static 'assets/img/thumb/profile.jpg' %}" alt=""></a>
                      </div>
                      <div class="col-8">
                        <h3 class="heading-style-4">لورم ایپسوم متن ساختگی با تولید سادگی</h3>
                        <p class="text">لورم ایپسوم متن ساختگی با تولید سادگی نامفهوم از صنعت چاپ</p>
                        <span class="date">{{post.author.first_name}} {{post.author.last_name}}/{{ post.published_at }}</span>
                      </div>
                    </div>
                  </div>
                  <div class="col-12 col-md-6 col-lg-12 item">
                    <div class="row">
                      <div class="col-4">
                        <a href="#"><img class="img-fluid" src="{% static 'assets/img/thumb/profile.jpg' %}" alt=""></a>
                      </div>
                      <div class="col-8">
                        <h3 class="heading-style-4">لورم ایپسوم متن ساختگی با تولید سادگی</h3>
                        <p class="text">لورم ایپسوم متن ساختگی با تولید سادگی نامفهوم از صنعت چاپ</p>
                        <span class="date">{{post.author.first_name}} {{post.author.last_name}}/{{ post.published_at }}</span>
                      </div>
                    </div>
                  </div>
                  <div class="col-12 col-md-6 col-lg-12 item">
                    <div class="row">
                      <div class="col-4">
                        <a href="#"><img class="img-fluid" src="{% static 'assets/img/thumb/profile.jpg' %}" alt=""></a>
                      </div>
                      <div class="col-8">
                        <h3 class="heading-style-4">لورم ایپسوم متن ساختگی با تولید سادگی</h3>
                        <p class="text">لورم ایپسوم متن ساختگی با تولید سادگی نامفهوم از صنعت چاپ</p>
                        <span class="date">{{post.author.first_name}} {{post.author.last_name}}/{{ post.published_at }}</span>
                      </div>
                    </div>
                  </div>
                  <div class="col-12 col-md-6 col-lg-12 item">
                    <div class="row">
                      <div class="col-4">
                        <a href="#"><img class="img-fluid" src="{% static 'assets/img/thumb/profile.jpg' %}" alt=""></a>
                      </div>
                      <div class="col-8">
                        <h3 class="heading-style-4">لورم ایپسوم متن ساختگی با تولید سادگی</h3>
                        <p class="text">لورم ایپسوم متن ساختگی با تولید سادگی نامفهوم از صنعت چاپ</p>
                        <span class="date">{{post.author.first_name}} {{post.author.last_name}}/{{ post.published_at }}</span>
                      </div>
                    </div>
                  </div>
                </div>
              </div>

              <div class="news-letter border-box-2 overflow_hidden mt-4 d-none d-lg-block">
                <div class="header-section">
                  <div class="row">
                    <div class="col-6">
                      <h3 class="heading-style-3">خبرنامه</h3>
                    </div>
                    <div class="col-6"></div>
                  </div>
                </div>
                <div class="content">
                  <h4 class="heading-style-4">اشتراک بگیرید</h4>
                  <p class="text">{{post.summary}}</p>
                  <div class="form-group width-full">
                    <input type="email" class="form-control" id="exampleInputEmail1" aria-describedby="emailHelp" placeholder="نام شما">
                  </div>
                  <div class="form-group width-full">
                    <input type="password" class="form-control" id="exampleInputPassword1" placeholder="ایمیل یا آیدی شما">
                  </div>
                  <div class="row">
                    <div class="col-4">
                      <label class="cutomized-form-radio">روزانه
                        <input type="radio" checked="checked" name="radio">
                        <span class="checkmark"></span>
                      </label>
                    </div>
                    <div class="col-4">
                      <label class="cutomized-form-radio">هفتگی
                        <input type="radio" checked="checked" name="radio">
                        <span class="checkmark weekly"></span>
                      </label>
                    </div>
                    <div class="col-4">
                      <label class="cutomized-form-radio">ماهانه
                        <input type="radio" checked="checked" name="radio">
                        <span class="checkmark"></span>
                      </label>
                    </div>
                  </div>
                  <a class="btn_1 center-box width-full text-center" href="#">خرید بلیط</a>
                </div>
              </div>

              <div class="social-media-2 mt-3">
                <div class="row">
                  <div class="col-4">
                    <div class="facebook item">
                      <a class="icon" href="#"><i class="fa fa-facebook" aria-hidden="true"></i></a>
                      <a class="action" href="#"><h5>SUSCRIBE</h5></a>
                      <p>5400 LIKES</p>
                    </div>
                  </div>
                  <div class="col-4">
                    <div class="twitter item">
                      <a class="icon" href="#"><i class="fa fa-twitter" aria-hidden="true"></i></a>
                      <a class="action" href="#"><h5>SUSCRIBE</h5></a>
                      <p>5400 LIKES</p>
                    </div>
                  </div>
                  <div class="col-4">
                    <div class="rss item">
                      <a class="icon" href="#"><i class="fa fa-rss" aria-hidden="true"></i></a>
                      <a class="action" href="#"><h5>SUSCRIBE</h5></a>
                      <p>5400 LIKES</p>
                    </div>
                  </div>
                </div>
              </div>
            </div>
          </div>
        </div>
      </div>
    </div>
</main>

kernel/media/templates/blog/post_list.html
{% extends 'shared/master.html' %}
{% load static %}
{% block body %}

<main>
    <div class="banner_3">
      <h1 class="heading-style-1">
        اخبار
      </h1>
      <div class="location">
        <a href="#">خانه</a>
        <span>/</span>
        <a href="#">اخبار</a>
        <span>/</span>
        <a class="active" href="#">لیست</a>
      </div>
    </div>

    <div class="news-section">
      <div class="container">
        <div class="row">
          <div class="col-lg-8 right_side news-list">            
            {% for post in posts %}
            <div class="col-12 mt-4">
                <div class=" border-box-2">
                  <div class="row">
                    <div class="col-md-6">
                      <img class="img-fluid news-image" src="{{ post.banner.url }}" alt="post.slug">
                    </div>
                    <div class="col-md-6 news-content">
                      <a class="title" href="{% url 'blog:post' slug=post.slug %}">{{ post.title }}</a>
                      <br>
                      <span class="date">{{ post.published_at }}</span>
                      <p class="text">
                        {{ post.summary }}
                      </p>
                      <a class="btn_2" href="{% url 'blog:post' slug=post.slug %}">بیشتر بخوانید</a>
                      <hr class="hr-divider-1">
                      <hr class="hr-divider-2">
                      <div class="social">
                        <div class="profile">
                          <img src="{% static 'assets/img/thumb/profile.jpg' %}" alt="{{ post.author.first_name }} {{ post.author.last_name }}">
                         <span class="name">{{ post.author.first_name }} {{ post.author.last_name }}</span>
                        </div>
                        <div class="user-input seen-count">
                          <i class="fa fa-eye" aria-hidden="true"></i>
                          <span class="count">251</span>
                        </div>
                        <div class="user-input like liked">
                          <button class="like liked" href="#" role="button">
                            <i class="fa fa-heart-o" aria-hidden="true"></i>
                            <i class="fa fa-heart" aria-hidden="true"></i>
                          </button>
                          <span class="count">251</span>
                        </div>
                      </div>
                    </div>
                  </div>
                </div>
              </div>
            {% endfor %}
            

            
            <ul class="pagination left-margin">
              <li class="page-item active"><a class="page-link" href="#">1</a></li>
              <li class="page-item"><a class="page-link" href="#">2</a></li>
              <li class="page-item"><a class="page-link" href="#">3</a></li>
              <li><i class="fa fa-ellipsis-h mt-2" aria-hidden="true"></i></li>
              <li class="page-item"><a class="page-link" href="#">10</a></li>
              <li class="page-item"><a class="page-link" href="#">11</a></li>
              <li class="page-item"><a class="page-link" href="#">12</a></li>
            </ul>
          </div>
          <div class="col-lg-4 left_side d-none d-lg-block">
            <div class="col-md-12">
              <div class="new-news border-box-2 overflow_hidden">
                <div class="header-section">
                  <div class="row">
                    <div class="col-6">
                      <h3 class="heading-style-3">خبر جدید</h3>
                    </div>
                    <div class="col-6"></div>
                  </div>
                </div>
                <div class="row">
                  <div class="col-12 col-md-6 col-lg-12 item">
                    <div class="row">
                      <div class="col-4">
                        <a href="#"><img class="img-fluid" src="assets/img/thumb/profile.jpg" alt=""></a>
                      </div>
                      <div class="col-8">
                        <h3 class="heading-style-4">لورم ایپسوم متن ساختگی با تولید سادگی</h3>
                        <p class="text">لورم ایپسوم متن ساختگی با تولید سادگی نامفهوم از صنعت چاپ</p>
                        <span class="date">۴ بهمن . ۱۳۹۷ / سپهر اکبرزاده</span>
                      </div>
                    </div>
                  </div>
                  <div class="col-12 col-md-6 col-lg-12 item">
                    <div class="row">
                      <div class="col-4">
                        <a href="#"><img class="img-fluid" src="assets/img/thumb/profile.jpg" alt=""></a>
                      </div>
                      <div class="col-8">
                        <h3 class="heading-style-4">لورم ایپسوم متن ساختگی با تولید سادگی</h3>
                        <p class="text">لورم ایپسوم متن ساختگی با تولید سادگی نامفهوم از صنعت چاپ</p>
                        <span class="date">۴ بهمن . ۱۳۹۷ / سپهر اکبرزاده</span>
                      </div>
                    </div>
                  </div>
                  <div class="col-12 col-md-6 col-lg-12 item">
                    <div class="row">
                      <div class="col-4">
                        <a href="#"><img class="img-fluid" src="assets/img/thumb/profile.jpg" alt=""></a>
                      </div>
                      <div class="col-8">
                        <h3 class="heading-style-4">لورم ایپسوم متن ساختگی با تولید سادگی</h3>
                        <p class="text">لورم ایپسوم متن ساختگی با تولید سادگی نامفهوم از صنعت چاپ</p>
                        <span class="date">۴ بهمن . ۱۳۹۷ / سپهر اکبرزاده</span>
                      </div>
                    </div>
                  </div>
                  <div class="col-12 col-md-6 col-lg-12 item">
                    <div class="row">
                      <div class="col-4">
                        <a href="#"><img class="img-fluid" src="assets/img/thumb/profile.jpg" alt=""></a>
                      </div>
                      <div class="col-8">
                        <h3 class="heading-style-4">لورم ایپسوم متن ساختگی با تولید سادگی</h3>
                        <p class="text">لورم ایپسوم متن ساختگی با تولید سادگی نامفهوم از صنعت چاپ</p>
                        <span class="date">۴ بهمن . ۱۳۹۷ / سپهر اکبرزاده</span>
                      </div>
                    </div>
                  </div>
                </div>
              </div>

              <div class="next-match border-box-2 overflow_hidden mt-4 d-none d-lg-block">
                <div class="header-section">
                  <div class="row">
                    <div class="col-6">
                      <h3 class="heading-style-3">بازی بعدی</h3>
                    </div>
                    <div class="col-6"></div>
                  </div>
                </div>
                <div class="row mx-0 relative">
                  <h4 class="heading-style-3">لورم ایپسوم متن ساختگی با تولید سادگی</h4>
                  <p class="date-match">15:00 ، 1397 ، تیر 10 ، جمع</p>
                  <div class="row mx-0 width-full">
                    <div class="col-5"><img class="img-fluid team" src="assets/img/thumb/team_2.png" alt=""></div>
                    <div class="col-2">
                      <p class="versous">VS</p>
                    </div>
                    <div class="col-5"><img class="img-fluid team" src="assets/img/thumb/team_1.png" alt=""></div>
                  </div>
                  <div class="col-12">
                    <a class="btn_1" href="#">خرید بلیط</a>
                  </div>
                  <p class="start-at">شروع در</p>
                  <div class="time-left col-12">
                    <div class="time">
                      <p class="faNum countDown_1" id="firstClock"></p>
                    </div>
                    <div class="time-letters">
                      <ul class="list-inline text-center">
                        <li class="list-inline-item"><span>دقیقه</span></li>
                        <li class="list-inline-item"><span>دقیقه</span></li>
                        <li class="list-inline-item"><span>دقیقه</span></li>
                        <li class="list-inline-item"><span>دقیقه</span></li>
                      </ul>
                    </div>
                  </div>
                </div>
              </div>

              <div class="news-letter border-box-2 overflow_hidden mt-4">
                <div class="header-section">
                  <div class="row">
                    <div class="col-6">
                      <h3 class="heading-style-3">خبرنامه</h3>
                    </div>
                    <div class="col-6"></div>
                  </div>
                </div>
                <div class="content">
                  <h4 class="heading-style-4">اشتراک بگیرید</h4>
                  <p class="text">لورم ایپسوم متن ساختگی با تولید سادگی نامفهوم از صنعت چاپ و با استفاده از طراحان گرافیک است. چاپگرها و متون بلکه</p>
                  <div class="form-group width-full">
                    <input type="email" class="form-control" id="exampleInputEmail1" aria-describedby="emailHelp" placeholder="نام شما">
                  </div>
                  <div class="form-group width-full">
                    <input type="password" class="form-control" id="exampleInputPassword1" placeholder="ایمیل یا آیدی شما">
                  </div>
                  <div class="row">
                    <div class="col-4">
                      <label class="cutomized-form-radio">روزانه
                        <input type="radio" checked="checked" name="radio">
                        <span class="checkmark"></span>
                      </label>
                    </div>
                    <div class="col-4">
                      <label class="cutomized-form-radio">هفتگی
                        <input type="radio" checked="checked" name="radio">
                        <span class="checkmark weekly"></span>
                      </label>
                    </div>
                    <div class="col-4">
                      <label class="cutomized-form-radio">ماهانه
                        <input type="radio" checked="checked" name="radio">
                        <span class="checkmark"></span>
                      </label>
                    </div>
                  </div>
                  <a class="btn_1 center-box width-full text-center" href="#">خرید بلیط</a>
                </div>
              </div>

              <div class="social-media-2 mt-3">
                <div class="row">
                  <div class="col-4">
                    <div class="facebook item">
                      <a class="icon" href="#"><i class="fa fa-facebook" aria-hidden="true"></i></a>
                      <a class="action" href="#"><h5>SUSCRIBE</h5></a>
                      <p>5400 LIKES</p>
                    </div>
                  </div>
                  <div class="col-4">
                    <div class="twitter item">
                      <a class="icon" href="#"><i class="fa fa-twitter" aria-hidden="true"></i></a>
                      <a class="action" href="#"><h5>SUSCRIBE</h5></a>
                      <p>5400 LIKES</p>
                    </div>
                  </div>
                  <div class="col-4">
                    <div class="rss item">
                      <a class="icon" href="#"><i class="fa fa-rss" aria-hidden="true"></i></a>
                      <a class="action" href="#"><h5>SUSCRIBE</h5></a>
                      <p>5400 LIKES</p>
                    </div>
                  </div>
                </div>
              </div>
            </div>
          </div>
        </div>
      </div>
    </div>
</main>
{% endblock %}

kernel/media/templates/blog/product.html
{% extends 'shared/site.html' %}
{% if post %}
    <p>{{ post }}</p>
    <p>{{ post.summary }}</p>
    <p>{{ post.content }}</p>
    <p>{{ post.uid }}</p>
{% else %}
    we don't find any post.
{% endif %}

kernel/media/templates/blog/products.html
{% extends 'shared/site.html' %}
{% block body %}
<h1>List of products</h1>
<ul>
    {% if latest_posts %}
    {% for post in latest_posts %}
        {{ post }}
    {% endfor %}
    
    {% else %}
        <p>We don't have any post</p>
    {% endif %}
</ul>
{% endblock %}